namespace NanoScript.Tests.Common;

enum TestToken {
	SIMPLE,SOURCE,STRING,IDENTICAL,
	EMPTY, NON_EMPTY, LARGE,
	AB, ABC, BC,
	LOW, PRIORITY, VALUES,
	HIGH, SPECIAL, CHARACTERS,
	SPECIAL_CHARS, Token1, Token2,
	Token3
}