script         := { statement } ;

statement      := definition 
			    | function 
			    | control_structure 
			    | expression 
			    | assignment 
			    | include 
			    | struct 
			    | package 
			    | error_handling 
			    | comment ;

assignment     := "let" IDENTIFIER [ value_list ] ;
definition     := "def" IDENTIFIER [ value ] ;
set     	   := "set" IDENTIFIER [ value ] ;
function       := "fnc" IDENTIFIER [ parameter_list ] ":" { statement } "ret" [ value_list ] ;
function_call  := "cll" IDENTIFIER { value } ;
while_loop     := "whl" condition { statement } "ext" ;
if_statement   := "iff" condition { statement } [ "elf" condition { statement } ] [ "els" { statement } ] "ext" ;

for_loop       := "for" IDENTIFIER value condition value [ value ] { statement } "ext" ;
control_structure := if_statement | while_loop | for_loop ;

include        := "inc" file_path [ IDENTIFIER ] ;

struct         := "tbl" IDENTIFIER [ parameter_list ] { statement } ;
package        := "pck" IDENTIFIER { statement } ;
error_handling := "err" error_code [ message ] ;

expression     := operation | function_call ;

value          := IDENTIFIER | NUMBER | STRING | character | array | struct_instance ;
value_list     := value { value } ;
parameter_list := IDENTIFIER { IDENTIFIER } ;
condition      := expression;
operation      := value operator value ;
array          := IDENTIFIER "[" [ value { "," value } ] "]" ;
struct_instance := IDENTIFIER { value } ;

comment        := "#" { any_character } ;


file_path      := STRING ;
error_code     := NUMBER ;
message        := STRING ;

expression 	   := literal
               | unary
               | binary
               | grouping;

literal        := NUMBER | STRING | "true" | "false" | "nil" ;
grouping       := "(" expression ")" ;
unary          := ( "-" | "!" ) expression;
binary         := expression operator expression;
operator       := "==" | "!=" | "<" | "<=" | ">" | ">="
               | "+"  | "-"  | "*" | "/";

logical_operator := "EQL" | "LES" | "GRT" | "TRU" | "FLS" ;

IDENTIFIER     := "[\\.]?{WORD}([\\.]{WORD})*([\\:]{WORD})?";
NUMBER         := "-?(0[xX][0-9a-fA-F]+|\d*[.]\d+([eE][+-]?\d+)?|\d+([.]\d*)?([eE][+-]?\d+)?)";
STRING         := "'(\\.|[^'\\])*'" ;
character      := ".*" ;