<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BetterConsoleTables" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
        <PackageReference Include="Newtonsoft.Json"/>
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="src\NanoScript\Parser\Parser.Expression.cs">
        <DependentUpon>Parser.cs</DependentUpon>
      </Compile>
      <Compile Update="src\NanoScript\Parser\Parser.Statement.cs">
        <DependentUpon>Parser.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\GitHub\Parseus\Parseus\Parseus.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\NanoScript\ParserV2\" />
    </ItemGroup>

</Project>
