<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Remove="Terminal.Gui" />
        <PackageReference Remove="SkiaSharp.Views.WindowsForms" />
        <PackageReference Remove="SkiaSharp" />
        <PackageReference Remove="Silk.NET.Windowing.Extensions.Veldrid" />
        <PackageReference Remove="Silk.NET.Windowing.Sdl" />
        <PackageReference Remove="Silk.NET.Windowing.Extensions" />
        <PackageReference Remove="Silk.NET.OpenGL.Extensions.ImGui" />
        <PackageReference Remove="Silk.NET.Input" />
        <PackageReference Remove="Silk.NET" />
        <PackageReference Remove="rlImgui-cs" />
        <PackageReference Remove="Raylib_ImGui" />
        <PackageReference Remove="Raylib_Extensions" />
        <PackageReference Remove="Raylib-CsLo" />
        <PackageReference Remove="Raylib-cs" />
        <PackageReference Remove="Microsoft.CodeAnalysis.Workspaces.Common" />
        <PackageReference Remove="Microsoft.CodeAnalysis.CSharp.Workspaces" />
        <PackageReference Remove="Microsoft.CodeAnalysis.CSharp" />
        <PackageReference Remove="Microsoft.AspNetCore.Components.WebAssembly.DevServer" />
        <PackageReference Remove="Microsoft.CodeAnalysis.Common" />
        <PackageReference Remove="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Remove="MessagePack" />
        <PackageReference Remove="LiteDB" />
        <PackageReference Remove="ImGui.NET.Docking" />
        <PackageReference Remove="ImGui.NET" />
        <PackageReference Remove="Image-Sharp.InteractiveExtension" />
        <PackageReference Remove="HtmlAgilityPack" />
        <PackageReference Remove="GtkSharp" />
        <PackageReference Remove="Flecs.NET.Bindings.Release" />
        <PackageReference Remove="Flecs.NET.Release" />
        <PackageReference Remove="EnTTSharp" />
        <PackageReference Remove="DotTiled" />
        <PackageReference Remove="BetterConsoleTables" />
        <PackageReference Remove="BetterConsoles.Core" />
        <PackageReference Remove="BetterConsoles.Colors" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="src\NanoScript\Parser\Parser.Expression.cs">
        <DependentUpon>Parser.cs</DependentUpon>
      </Compile>
      <Compile Update="src\NanoScript\Parser\Parser.Statement.cs">
        <DependentUpon>Parser.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\NanoScript\ParserV2\Ast\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\GitHub\Parseus\Parseus.csproj" />
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BetterConsoles.Colors" />
      <PackageReference Include="BetterConsoles.Core" />
      <PackageReference Include="BetterConsoleTables" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    </ItemGroup>

</Project>
